### ISSUE TITLE
Doesn't like title.goeswhere.com

### ISSUE THREAD

**Issue by FauxFaux** [FauxFaux/limnoria-plugins#2]
Trying to use https://title.goeswhere.com/test results in an error, and the error is not logged.

This is not acceptable.

**Comment by FodT** [comment]
Server is returning content type `application/octet-stream, text/html` instead of content type `application/octet-stream; text/html`

Application is also only taking the first mimetype (in this case "application/octet-stream, text/html" but ideally "application/octet-stream" and matching against acceptable mimetypes (by default only "text/html")
